version: "3.7"

services:
  app:
    build:
      context: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 8888:8888

  #the services below is a short hand to use npm in docker context
  test:
    build:
      context: .
    command: npm run test
    volumes:
      - .:/app

  lint:
    build:
      context: .
    command: npm run lint
    volumes:
      - .:/app
  format:
    build:
      context: .
    command: npm run format
    volumes:
      - .:/app

networks:
  default:
    name: penseapp-discord-notification